# Generated by Django 6.0.4 on 2026-04-28 15:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('C', 'Corrente'), ('P', 'Poupança'), ('I', 'Investimento'), ('X', 'Dinheiro'), ('K', 'Cartão de Crédito')], max_length=1)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cor', models.CharField(default='#6c757d', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#007bff', help_text='Cor para identificação nos gráficos', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MetaEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_poupado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1)),
                ('icone', models.CharField(default='bi-cash-stack', help_text='Classe do Bootstrap Icons', max_length=50)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado')], default='C', max_length=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('recorrente', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.conta')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.membrofamilia')),
                ('tags', models.ManyToManyField(blank=True, to='financas.tag')),
            ],
        ),
    ]
