# Generated by Django 6.0.4 on 2026-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='dia_fechamento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia que a fatura fecha', null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia que a fatura vence', null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Apenas para Cartão de Crédito', max_digits=15),
        ),
        migrations.AddField(
            model_name='transacao',
            name='id_parcelamento',
            field=models.CharField(blank=True, help_text='ID único para agrupar parcelas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='parcela_atual',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transacao',
            name='total_parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
