# Generated by Django 6.0.4 on 2026-04-28 19:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_alter_conta_dia_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='eh_transferencia',
            field=models.BooleanField(default=False, help_text='Indica se esta transação faz parte de uma transferência entre contas.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default='bi-cash-stack', help_text='Ícone do Bootstrap Icons (ex: bi-cart, bi-house).', max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='pai',
            field=models.ForeignKey(blank=True, help_text='Selecione se esta for uma subcategoria (ex: Almoço é sub de Alimentação).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financas.categoria'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='cor',
            field=models.CharField(default='#6c757d', help_text='Cor de identificação visual da conta.', max_length=7),
        ),
        migrations.AlterField(
            model_name='conta',
            name='dia_fechamento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia que a fatura do cartão fecha.', null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia que a fatura do cartão vence.', null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Limite total (apenas para Cartões de Crédito).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo que você já possui nesta conta hoje.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='cor',
            field=models.CharField(default='#007bff', help_text='Cor usada nos gráficos para identificar este membro.', max_length=7),
        ),
        migrations.AlterField(
            model_name='metaeconomia',
            name='data_limite',
            field=models.DateField(help_text='Data pretendida para realizar o objetivo.'),
        ),
        migrations.AlterField(
            model_name='metaeconomia',
            name='valor_objetivo',
            field=models.DecimalField(decimal_places=2, help_text='Quanto você quer juntar?', max_digits=15),
        ),
        migrations.AlterField(
            model_name='metaeconomia',
            name='valor_poupado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quanto já possui guardado hoje?', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_limite',
            field=models.DecimalField(decimal_places=2, help_text='Limite máximo de gastos para esta categoria no mês.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='recorrencia',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Desmarque para parar de gerar esta transação automaticamente.'),
        ),
        migrations.AlterField(
            model_name='recorrencia',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(help_text='Dia do mês que esta conta vence (ex: 1 a 31).'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(help_text='Conta por onde o dinheiro sairá/entrará.', on_delete=django.db.models.deletion.CASCADE, to='financas.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=datetime.date.today, help_text='Data da compra ou do recebimento.'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='membro',
            field=models.ForeignKey(blank=True, help_text='Quem realizou esta transação?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.membrofamilia'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado')], default='C', help_text='Pendente: ainda não saiu do banco. Confirmado: já conferido no extrato.', max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas para agrupar (ex: Viagem, Reforma).', to='financas.tag'),
        ),
        migrations.CreateModel(
            name='RegraImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_contem', models.CharField(help_text='Texto a buscar na descrição do banco (ex: UBER).', max_length=100)),
                ('categoria', models.ForeignKey(help_text='Categoria a ser aplicada automaticamente.', on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
            ],
        ),
    ]
