# Generated by Django 6.0.4 on 2026-04-29 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_transacao_eh_transferencia_alter_categoria_icone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='classe_abc',
            field=models.CharField(choices=[('E', 'Essencial (50%)'), ('L', 'Estilo de Vida (30%)'), ('I', 'Investimento/Divida (20%)'), ('N', 'Nao se aplica')], default='N', help_text='Classificacao para a regra 50/30/20.', max_length=1),
        ),
        migrations.AddField(
            model_name='transacao',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Anexe uma foto ou PDF do comprovante.', null=True, upload_to='comprovantes/%Y/%m/'),
        ),
    ]
