# Generated by Django 6.0.4 on 2026-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_patrimoniohistorico_categoria_classe_abc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(help_text='O que este relatório deve analisar?')),
                ('tipo', models.CharField(choices=[('T', 'Tradicional (Tabelas)'), ('I', 'IA (Analítico Narrativo)')], default='T', max_length=1)),
                ('query_base', models.CharField(blank=True, help_text='Termo de busca padrão (ex: Uber, Restaurante) se aplicável.', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
